### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by kleinash** [phobon/RobotOS.jl#13]
Hi,

I get an error when bootstrapping for test:

###
$ python echonode.py 
Traceback (most recent call last):
  File "echonode.py", line 4, in <module>
    import rospy
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ImportError: No module named 'rospkg'
###

But I have rospkg installed.. is it my version of ros?

Thx

**Comment by phobon** [comment]
Hello,

I think I've seen that error before when a different version of python was running from the one ROS expected. Not sure how to go about troubleshooting it though.

Anyways, this is unrelated to the Julia package because echonode is a completely normal ROS python node. If you can't it figured out, [ROS answers](http://answers.ros.org) would be the place to go.
